version: "3.9"

services:
  db:
    image: postgres:16
    container_name: my_postgres
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      # Named volume for data persistence
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my_etl_app
    depends_on:
      - db
    environment:
      - DB_NAME=mydb
      - DB_USER=postgres
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=5432
    # In case you have interactive prompts or want logs
    tty: true

volumes:
  pg_data:
